### ISSUE TITLE
'create_shader' is not defined

### ISSUE THREAD

**Issue by heyitsmalou** [kromond/OptiSkelForUEScripts#2]
Issue with running: 

_# make some materials with random colors_

Error occurs:

_**# Error: NameError: file <maya console> line 1: name 'create_shader' is not defined #**_ 

All other lines work fine (set all rotations to zeros / set tx and tz to zero on hips)

**Comment by kromond** [comment]
I think I fixed in the refactor

![image](https://github.com/kromond/OptiSkelForUEScripts/assets/5624947/88c7bd80-aa1e-41a3-afd8-61c031e4e16e)
