### ISSUE TITLE
MAYA plug-in problem

### ISSUE THREAD

**Issue by zw19860708** [kromond/OptiSkelForUEScripts#4]
I followed your tutorial to output a piece of motion capture data from the Motive software, and the options were set as in your tutorial.
![1](https://github.com/kromond/OptiSkelForUEScripts/assets/138918810/6a809c01-7942-43f6-83d6-2a51d6f8ed46)

Execute the following code in Maya's Python
import sys 
import maya.cmds as cmds
import maya.mel as mel 
import imp
import os

scriptDir = r"D:/Setup/OptiSkelForUEScripts-master/python/Maya"
sys.path.insert(0, scriptDir)

import OptiSkelPrep as osp

imp.reload(osp)

name_separator=':'

pose_file_path = os.path.join(scriptDir, "jsonPoses")

skelToTest = cmds.ls( "*{}Root".format(name_separator))[0]

root_joint, node_type, namespace = osp.set_up_optiFBX(name_separator, pose_file_path)

print(root_joint, node_type, namespace)

osp.make_geo_and_export(root_joint, node_type,name_separator, namespace)

The sequence frames of the skeletal animation are deleted, and meshes cannot be added to the bones. The bones take on the shape of standard T-POSE, as shown in the figure below.

![2](https://github.com/kromond/OptiSkelForUEScripts/assets/138918810/b9ecb52a-7387-4589-8717-e2f1d89f1f83)

Please tell me which part I have a problem with?

**Comment by kromond** [comment]
You will have to read the error messages and work it out
